// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH LOGIN REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH = "AUTH";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const PROFILE_USER_LOADED = "PROFILE_USER_LOADED";
export const PROFILE_NOT_EXISTS = "PROFILE_NOT_EXISTS";
export const PROFILE_USER_SUCCESS = "PROFILE_USER_SUCCESS";
export const PROFILE_USER_FAIL = "PROFILE_USER_FAIL";
export const PROFILES_LOADED = "PROFILES_LOADED";
export const INITIATE_EDITING = "INITIATE_EDITING";
export const PROFILE_RECIEVE_NOTIFICATION = "PROFILE_RECIEVE_NOTIFICATION";

// POST AND COMMENT
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";


//EVENT
export const GET_EVENT = "GET_EVENT";
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const ADD_EVENT = "ADD_EVENT";
export const EVENT_ERROR = "EVENT_ERROR";
